customhost = "itp.cbvkxab6tdeg.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "itp"
# custombucket = "amos-employee"
customregion = "us-east-1"
# customhost = "database-1.caldwcg5mkux.us-east-1.rds.amazonaws.com"
# customuser = "aws_user"
# custompass = "Bait3273"
# customdb = "database-1"
# custombucket = "amos-itp"
custombucket = "leongjingen-employee"
# customregion = "us-east-1"

